version: '3.8'

services:
  app:
    image: ghcr.io/chitsenghang/ccubank-ci:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ccubank-core
    env_file:
      - '.env'
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: ccu_postgres
    env_file:
      - '.env'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: ccu_redis
    env_file:
      - '.env'
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
