export const DEFAULT_DATE_FORMAT = 'YYYY-MM-DD';
export const DEFAULT_DATE_FORMAT_WITH_MONTH_AS_CHARACTER = 'DD-MMM-YYYY';
export const DEFAULT_DATE_HOUR_MINUTE_FORMAT_WITH_MONTH_AS_CHARACTER =
  'DD-MMM-YYYY HH:mm';
export const DEFAULT_TIME_FORMAT = 'HH:mm:ss';
export const DEFAULT_YEAR_FORMAT = 'YYYY';
export const DEFAULT_MONTH_FORMAT = 'MM';
export const DEFAULT_FULL_MONTH_FORMAT = 'MMM';
export const DEFAULT_HOUR_FORMAT = 'HH';
export const DEFAULT_DATE_TIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';
export const DEFAULT_DATE_HOUR_MINUTE_FORMAT = 'YYYY-MM-DD HH:mm';
export const DEFAULT_YEAR_MONTH_FORMAT = 'YYYY-MM';
export const DEFAULT_DAY_FORMAT = 'DD';
export const DEFAULT_HOUR_MINUTE_FORMAT = 'HH:mm';
export const DEFAULT_MINUTE_FORMAT = 'mm';
export const DEFAULT_SECOND_FORMAT = 'ss';
