name: ccubank-core deploy

env:
  PRIMARY_BRANCH: main

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version:  "20.18.2"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Lint
        run: yarn lint

  build:
    if: github.event_name == 'pull_request' && github.base_ref == $PRIMARY_BRANCH
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.TOKEN_GITHUB  }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner  }}/ccubank-core:latest .
          docker push ghcr.io/${{ github.repository_owner  }}/ccubank-core:latest

      - name: Clean up docker
        run: |
          docker system prune -f
          docker logout ghcr.io

  deploy:
    if: github.event_name == 'pull_request' && github.base_ref == $PRIMARY_BRANCH
    runs-on: ubuntu-latest
    needs: build
    env:
      REGISTRY_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      REGISTRY_USER_NAME: ${{ github.repository_owner }}
      SERVER_HOST: ${{ secrets.SERVER_HOST }}
      SERVER_USER: ${{ secrets.SERVER_USER }}
      COMPOSE_FILE_DIR: ./ccubank
      COMPOSE_FILE_NAME: docker-compose.yaml
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DB_USER: ${{secrets.DB_USER}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_DATABASE: ${{secrets.DB_DATABASE}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remote to server and Deploy
        run: |
          chmod +x ./scripts/ssh_setup.sh ./scripts/deploy.sh
          ./scripts/deploy.sh